import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useTheme } from '@/utils/store';
import { Menu, Sun, Moon, Bell, LogOut } from 'lucide-react';
import { Button } from './ui';
export const Header = ({ title = 'ClassConnect', onMenuClick, showNotifications = false, unreadCount = 0, }) => {
    const { isDark, toggleTheme } = useTheme();
    return (_jsx("header", { className: "sticky top-0 z-40 bg-gradient-to-r from-surface to-bg-light border-b border-border backdrop-blur-sm", children: _jsxs("div", { className: "flex items-center justify-between h-16 px-6", children: [_jsxs("div", { className: "flex items-center gap-4", children: [onMenuClick && (_jsx("button", { onClick: onMenuClick, className: "text-muted hover:text-text transition-colors", children: _jsx(Menu, { size: 24 }) })), _jsx("h1", { className: "text-2xl font-bold bg-gradient-to-r from-primary to-primary-light bg-clip-text text-transparent", children: title })] }), _jsxs("div", { className: "flex items-center gap-3", children: [showNotifications && (_jsxs("button", { className: "relative text-muted hover:text-text transition-colors focus-visible", children: [_jsx(Bell, { size: 20 }), unreadCount > 0 && (_jsx("span", { className: "absolute -top-1 -right-1 w-5 h-5 bg-red rounded-full text-xs text-white font-bold flex items-center justify-center", children: unreadCount > 99 ? '99+' : unreadCount }))] })), _jsx("button", { onClick: toggleTheme, className: "text-muted hover:text-text transition-colors p-2 focus-visible", "aria-label": "Toggle theme", children: isDark ? _jsx(Sun, { size: 20 }) : _jsx(Moon, { size: 20 }) })] })] }) }));
};
export const Sidebar = ({ isOpen, onClose, items, onLogout }) => {
    return (_jsxs(_Fragment, { children: [isOpen && (_jsx("div", { className: "fixed inset-0 bg-black/30 md:hidden z-20", onClick: onClose })), _jsxs("aside", { className: clsx('fixed md:static top-0 left-0 h-screen w-64 bg-surface border-r border-border overflow-y-auto transition-transform duration-300 z-30', isOpen ? 'translate-x-0' : '-translate-x-full md:translate-x-0'), children: [_jsxs("div", { className: "p-6 border-b border-border", children: [_jsx("h2", { className: "text-xl font-bold bg-gradient-to-r from-primary to-primary-light bg-clip-text text-transparent", children: "ClassConnect" }), _jsx("p", { className: "text-xs text-muted mt-1", children: "v2.0" })] }), _jsx("nav", { className: "p-4 flex flex-col gap-2", children: items.map((item) => (_jsxs("a", { href: item.href, className: clsx('flex items-center gap-3 px-4 py-2 rounded-xs transition-all duration-200', item.isActive
                                ? 'bg-primary/20 text-primary border-l-2 border-primary'
                                : 'text-muted hover:text-text hover:bg-surface-2'), children: [item.icon, _jsx("span", { className: "font-medium", children: item.label })] }, item.href))) }), _jsx("div", { className: "absolute bottom-0 left-0 right-0 p-4 border-t border-border", children: _jsxs(Button, { onClick: onLogout, variant: "ghost", className: "w-full justify-start gap-2", children: [_jsx(LogOut, { size: 18 }), "Logout"] }) })] })] }));
};
// Helper for imports
import { clsx } from 'clsx';
